image: registry.gitlab.com/citygro/docker-and-compose

services:
  - docker:dind
      
variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - test
#  - deploy

build:
  stage: build
  image: docker:latest
  script:
    - docker info
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker-compose build --pull -t "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" web
    - docker-compose push "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME" web

test:
  image: docker:latest 
  script:
    - docker-compose run web bundle exec rake db:create db:migrate db:test:prepare RAILS_ENV=test
    - docker-compose exec solr bin/solr create -c development -d /opt/config
    - docker-compose run web bundle exec rake
    - docker-compose run web bundle exec rake assets:precompile

#staging:
#  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
#  type: deploy
#  script:
#    - gem install dpl multi_json
#    - # TODO DEPLOY COMMAND dpl --provider=heroku --app=east-west-payroll-staging --api-key=$HEROKU_STAGING_API_KEY
#  only:
#    - master
#
#production:
#  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
#  type: deploy
#  script:
#    - gem install dpl multi_json
#    - # TODO DEPLOY COMMAND dpl --provider=heroku --app=east-west-payroll --api-key=$HEROKU_PRODUCTION_API_KEY
#  when: manual
